[package]
name = "metar"
version = "0.8.0"
authors = ["Lily Hopkins <lily@hpkns.uk>"]
edition = "2021"
description = "A fast METAR parsing library in pure Rust"
license = "MIT"
homepage = "https://github.com/lilopkins/metar-rs"
repository = "https://github.com/lilopkins/metar-rs"
readme = "README.md"

[dependencies]
annotate-snippets = "0.12.9"
pest = "2.8"
pest_derive = "2.8"

[dev-dependencies]
anyhow = "1.0"
async-trait = "0.1"
cucumber = "0.21"
futures = "0.3"

[[test]]
name = "cucumber"
harness = false
